transcripts/103.txt

Episode 103

---

transcripts/104.txt

Episode 104

---

transcripts/105.txt

Episode 105

---

transcripts/107.txt

Here's Episode 107.
Later,
Kevin

Episode 107

---

transcripts/111.txt

Episode 111

---

transcripts/114.txt

Episode 114

---

transcripts/115.txt

Episode 115

---

transcripts/116.txt

Episode 116

---

transcripts/118.txt

Episode 118

---

transcripts/119.txt

Episode 119

---

transcripts/121.txt

Episode 121

---

transcripts/122.txt

Episode 122

---

transcripts/123.txt

I guess I could have got this one in the last PR, but here it is ;)

Episode 123

---

transcripts/124.txt

Episode 124

---

transcripts/125.txt

Episode 125

---

transcripts/126.txt

Episode 126

---

transcripts/128.txt

Episode 128

---

transcripts/129.txt

Episode 129

---

transcripts/130.txt

Episode 130

---

transcripts/131.txt

I apologize I didn't get this to you sooner.  But at long last, here it is ;)

Episode 131

---

transcripts/134.txt

Episode 134

---

transcripts/139.txt

Episode 139

---

transcripts/140.txt

Episode 140

---

transcripts/143.txt

Hey Micheal, here's 143.  I wanted to let you know that the Backtrack's Player is not displaying on your website after our "Hicup" a couple of days ago.  Maybe it fell back to the HTML5 player and stayed there.  Anyway, our player is working and 143's transcript is available in it.  Let me know if you have any concerns or issues.
Merry Christmas,
Kevin

Episode 143

---

transcripts/144.txt

Episode 144

---

transcripts/145.txt

Episode 145

---

transcripts/146.txt

Episode 146

---

transcripts/149.txt

Episode 149

---

transcripts/150.txt

Episode 150

---

transcripts/152.txt

Episode 152

---

transcripts/153.txt

Episode 153

---

transcripts/154.txt

Episode 154

---

transcripts/156.txt

Episode 156

---

transcripts/157.txt

Here ya go. Another really interesting episode that brought back memories.  My first job out of grad school was writing flight software for the Space Station.  I got to see the Hubble launch on the Shuttle at Cape Canaveral.  Hopefully, the new telescopes will get approved.

Episode 157

---

transcripts/158.txt

Episode 158

---

transcripts/159.txt

Episode 159

---

transcripts/160.txt

Episode 160

---

transcripts/161.txt

Episode 161

---

transcripts/163.txt

Episode 163

---

transcripts/166.txt

Episode 166

---

transcripts/160.txt

Signed-off-by: Bahram Aghaei <aghaee.bahram@gmail.com>

Fix typos on episode 160

---

transcripts/121.txt

Signed-off-by: Bahram Aghaei <aghaee.bahram@gmail.com>
Thanks for episode 121 - MicroServices

fix typo on 121 episode

---

transcripts/167.txt

Episode 167

---

transcripts/171.txt

Episode 171

---

transcripts/172.txt

Episode 172

---

transcripts/174.txt

Episode 174

---

transcripts/052.txt

These are corrections to typos and replacing some of the placeholder time stamps with correct dialogue.

Fix typos in episode 52

---

transcripts/176.txt

Episode 176

---

transcripts/177.txt

Here ya go.  Sorry it took a while.

Episode 177

---

transcripts/178.txt

Episode 178

---

transcripts/181.txt

Episode 181

---

transcripts/182.txt

Episode 182

---

transcripts/183.txt

Episode 183

---

transcripts/184.txt

Episode 184

---

transcripts/185.txt

Episode 185

---

transcripts/186.txt

Episode 186

---

transcripts/187.txt

Episode 187

---

transcripts/188.txt

Episode 188

---

transcripts/192.txt

Episode 192

---

transcripts/194.txt

Episode 194

---

transcripts/196.txt

Episode 196

---

transcripts/200.txt

Episode 200

---

transcripts/202.txt

Episode 202

---

transcripts/204.txt

Episode 204

---

transcripts/206.txt

Episode 206

---

transcripts/207.txt

Episode 207

---

transcripts/208.txt

Episode 208

---

transcripts/209.txt

Episode 209

---

transcripts/212.txt

Episode 212

---

transcripts/213.txt

Episode 213

---

transcripts/214.txt

Episode 214

---

transcripts/215.txt

Episode 215

---

transcripts/216.txt

Episode 216

---

transcripts/001.txt

Minor change to the wording of the transcript so it makes sense and more closely matches original audio.

Minor transcript change to match original audio

---

transcripts/217.txt

Episode 217

---

transcripts/218.txt

Episode 218

---

transcripts/221.txt

Episode 221

---

transcripts/223.txt

Episode 223

---

transcripts/225.txt

Episode 225

---

transcripts/232.txt

Episode 232

---

transcripts/234.txt

Episode 234

---

transcripts/235.txt

Episode 235

---

transcripts/237.txt

Episode 237

---

transcripts/239.txt

Episode 239

---

transcripts/242.txt

Episode 242

---

transcripts/243.txt

Episode 243

---

transcripts/244.txt

Episode 244

---

transcripts/245.txt

Episode 245

---

transcripts/246.txt

Episode 246

---

transcripts/249.txt

Episode 249

---

transcripts/251.txt

Episode 251

---

transcripts/253.txt

Episode 253

---

transcripts/254.txt
transcripts/255.txt

Fixed Double Newline on 254 and 255.

Episodes 254 & 255
